---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - pvc.yaml
  - statefulset.yaml
  - ingress.yaml
  - image-automation.yaml
commonLabels:
  app.kubernetes.io/name: met-to-wg
  app.kubernetes.io/part-of: met-to-wg
